WebApp/WebApp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('login.urls', namespace="auth")),
    url(r'^tracker/', include('tracker.urls', namespace="tracker")),
    url(r'^home/', include('home.urls', namespace="home")),
]

WebApp/home/urls.py
from django.conf.urls import url
from home import views

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^choose_fields/$', views.choose_fields, name="choose_fields"),
    url(r'^submit_fields/$', views.submit_fields, name="submit_fields"),
]

WebApp/login/urls.py
from django.conf.urls import url
from login import views

urlpatterns = [
    url(r'^$', views.LoginAPIView.as_view()),
]

WebApp/tracker/urls.py
from django.conf.urls import url
from tracker import views

urlpatterns = [
    url(r'^activities/$', views.ActivityView.as_view()),
    url(r'^fields/$', views.FieldView.as_view()),
    url(r'^activityfieldeffects/$', views.ActivityFieldEffectView.as_view()),
]

WebApp/home/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

WebApp/tracker/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Activities(models.Model):
    name = models.CharField(max_length=64)
    description = models.CharField(max_length=255, null=True)
    class Meta:
        db_table = "Activities"

class Fields(models.Model):
    name = models.CharField(max_length=64)
    description = models.CharField(max_length=255, null=True)
    subfieldOf = models.ForeignKey("self", null=True)
    class Meta:
        db_table = "Fields"

class ActivityFieldEffects(models.Model):
    activity = models.ForeignKey(Activities)
    field = models.ForeignKey(Fields)
    effect = models.FloatField()
    class Meta:
        db_table = "ActivityFieldEffects"

class UserActivities(models.Model):
    user = models.ForeignKey(User)
    activity = models.ForeignKey(Activities)
    class Meta:
        db_table = "UserActivities"

class UserFields(models.Model):
    user = models.ForeignKey(User)
    field = models.ForeignKey(Fields)
    score = models.FloatField()
    class Meta:
        db_table = "UserFields"

#class UserActivityLogs(models.Model):
#    date = models.DateField()
#    activity = models.ForeignKey(Activities)
#    user = models.ForeignKey(User)
#    class Meta:
#        db_table = "UserActivityLogs"
#
#class UserFieldProgress(models.Model):
#    date = models.DateField()
#    user = models.ForeignKey(User)
#    field = models.ForeignKey(Fields)
#    score = models.FloatField()
#    class Meta:
#        db_table = "UserFieldProgress"
#    
#class UserSubfieldProgress(models.Model):
#    date = models.DateField()
#    user = models.ForeignKey(User)
#    field = models.ForeignKey(Subfields)
#    score = models.FloatField()
#    class Meta:
#        db_table = "UserSubfieldProgress"

WebApp/home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from tracker.models import Activities, Fields, UserFields, ActivityFieldEffects
import json
# Create your views here.

@login_required
def home(request):
    context = {}
    context["userfields"] = UserFields.objects.filter(user=request.user)
    context["useractivities"] = ActivityFieldEffects.objects.filter(field_id__in=context["userfields"].values_list('field_id', flat=True))
    return render(request, 'home/home.html', context=context)

@login_required
def choose_fields(request):
    context = {}
    context["fields"] = Fields.objects.all().exclude(id__in=UserFields.objects.filter(user=request.user).values_list('field_id', flat=True)).filter(subfieldOf__isnull=True)
    return render(request, 'home/choose_fields.html', context=context)

@login_required
def submit_fields(request):
    post_data = request.POST.dict()
    for k, v in post_data.iteritems():
        if v == "true":
            u = UserFields(user=request.user, field_id=k, score=1)
            u.save()
    return redirect("home:home")

WebApp/login/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from rest_framework.views import APIView
from utilities.HttpResponses import HttpResponseError, HttpResponseSuccess

# Create your views here.

class LoginAPIView(APIView):
    def post(self, request):
        data = request.POST.dict()
        if 'username' not in data or 'password' not in data:
            return HttpResponseError("Username/Password is required", 400)
        user = authenticate(username=data['username'], password=data['password'])
        if user is None:
            return HttpResponseError("Invalid username/password", 404)
        login(request, user)
        context = {}
        return redirect("home:home")

    def get(self, request):
        return render(request, 'login/login.html')

WebApp/tracker/views.py
from django.shortcuts import render
from rest_framework import generics
from tracker.models import Activities, Fields, ActivityFieldEffects
from tracker.serializers import ActivitySerializer, FieldSerializer, ActivityFieldEffectSerializer
# Create your views here.

class ActivityView(generics.ListCreateAPIView):
    queryset = Activities.objects.all()
    serializer_class = ActivitySerializer

class FieldView(generics.ListCreateAPIView):
    queryset = Fields.objects.all()
    serializer_class = FieldSerializer

class ActivityFieldEffectView(generics.ListCreateAPIView):
    queryset = ActivityFieldEffects.objects.all()
    serializer_class = ActivityFieldEffectSerializer

WebApp/home/templates/home/choose_fields.html
<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
	<title>"1-percent-a-day"</title>
    </head>
    
    <body>
        <h2>Choose all the fields you are interested in improving:</h2>
        <form action={% url "home:submit_fields" %} method="post">
            {% csrf_token %}
            {% for f in fields %}
                <input type="radio" name={{ f.id }} value=true>{{ f.name }}</input><br>
            {% endfor %}
            <button type="submit">Submit</button>
        </form>
    </body>
</html>

WebApp/home/templates/home/home.html
<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
	<title>"1-percent-a-day"</title>
    </head>
    
    <body>
        <h2>Summary</h2>
        <h4>You are interested in improving these fields:</h4>
        <ul>
            {% for uf in userfields %}
                <li>{{ uf.field.name }}: {{ uf.score }}</li>
            {% endfor %}
        </ul>
        <h4>Your list of activities:</h4>
        <ul>
            {% for ua in useractivities %}
               <li>{{ ua.activity.name }}</li> 
            {% endfor %}
        </ul>
        <span><a href={% url "home:choose_fields" %}>Add more interests</a></span>&nbsp;&nbsp;&nbsp;&nbsp;
    </body>
</html>

WebApp/login/templates/login/home.html
<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
	<title>"1-percent-a-day"</title>
    </head>
    <body>
        <span>Hello there!</span>
    </body>
</html>

WebApp/login/templates/login/login.html
<form action="" method="post">
  {%csrf_token%}
  <input type="text" name="username"></input>
  <input type="password" name="password"></input>
  <button type="submit"></button>
</form>